version: "3"

services:
  mysql:
    image: mysql/mysql-server:8.0
    command: mysqld
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      MYSQL_DATABASE: sample_proj
      TZ: "Asia/Tokyo"
    ports:
      - 3306:3306
    volumes:
      - ./docker/db/entrypoint:/docker-entrypoint-initdb.d
      - ./docker/db/data:/var/lib/mysql
      - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf

  backend:
    build:
      context: .
      dockerfile: ./packages/backend/Dockerfile
    environment:
      DATABASE_URL: mysql://docker:docker@mysql:3306/sample_proj
    tty: true
    depends_on:
      - mysql
    ports:
      - "3300:3300"

  frontend:
    build:
      context: .
      dockerfile: ./packages/frontend/Dockerfile
    environment:
      SERVER_BACKEND_URI: http://backend:3300
      PUBLIC_BACKEND_URI: http://localhost:3300
    tty: true
    depends_on:
      - backend
    ports:
      - "3000:3000"
    volumes:
      - /app/packages/frontend/node_modules
