import type { NextPage } from "next";
import Head from "next/head";

import { TaskManager } from "@/components/taskmanager/TaskManager";
import { TaskManager as TaskManagerDB } from "@/components/taskmanagerdb/TaskManager";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div className="container mx-auto">
          <div className="flex flex-wrap">
            <div className="w-full lg:w-1/2">
              <TaskManager />
            </div>
            <div className="w-full lg:w-1/2">
              <TaskManagerDB />
            </div>
          </div>
        </div>
      </main>
    </div>
  );
};

export default Home;
